### ISSUE TITLE
Some problem to launch demo in jfrtracer branch.

### ISSUE THREAD

**Issue by gunlee01** [thegreystone/problematic-microservices#1]
I met the trouble below after run `mvn package` the project and `./target/bin/xxxService`.
Did I miss something?

`Failed to scan [file:/xxx/problematic-microservices/robotshop-order-service/target/repo/org/glassfish/jaxb/jaxb-jxc/2.4.0-b180725.0644/txw2-2.4.0-b180725.0644.jar] from classloader hierarchy`

**Comment by gunlee01** [comment]
```
Failed to scan [file:/Users/gunlee/Documents/workspace/github/problematic-microservices/robotshop-customer-service/target/repo/org/glassfish/jaxb/jaxb-jxc/2.4.0-b180725.0644/txw2-2.4.0-b180725.0644.jar] from classloader hierarchy
java.io.FileNotFoundException: /Users/gunlee/Documents/workspace/github/problematic-microservices/robotshop-customer-service/target/repo/org/glassfish/jaxb/jaxb-jxc/2.4.0-b180725.0644/txw2-2.4.0-b180725.0644.jar (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:130)
	at org.apache.tomcat.util.compat.JreCompat.jarFileNewInstance(JreCompat.java:188)
	at org.apache.tomcat.util.scan.JarFileUrlJar.<init>(JarFileUrlJar.java:65)
	at org.apache.tomcat.util.scan.JarFactory.newInstance(JarFactory.java:49)
	at org.apache.tomcat.util.scan.StandardJarScanner.process(StandardJarScanner.java:374)
	at org.apache.tomcat.util.scan.StandardJarScanner.processURLs(StandardJarScanner.java:309)
	at org.apache.tomcat.util.scan.StandardJarScanner.doScanClassPath(StandardJarScanner.java:266)
	at org.apache.tomcat.util.scan.StandardJarScanner.scan(StandardJarScanner.java:229)
	at org.apache.catalina.startup.ContextConfig.processJarsForWebFragments(ContextConfig.java:1888)
	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1116)
	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:765)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:299)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5154)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1421)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1411)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by thegreystone** [comment]
I typically only get that when running on JDK8. When running on JDK11, using the launchers, I don't see that problem. I haven't bothered to check why the problem occurs, but as far as I can tell it doesn't affect the actual running of the micro service. I.e. even if you get that exception, it is only a failure to scan some zip files (for what I assume is annotations), and it will not affect the running of the micro service.

**Comment by gunlee01** [comment]
Thank you. Let me check something more.

**Comment by thegreystone** [comment]
Hi @gunlee01!

Did you find out a good way to do something about this? Since I am registering stuff explicitly, I think it's probably ok to disable the scanning altogether, however that is done.
